### ISSUE TITLE
env.test.ini missing from npm version

### ISSUE THREAD

**Issue by zaventh** [warrenca/generator-restify-es-6#2]
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/generators/app/templates/env.test.ini
    at EditionInterface.exports._copySingle (/home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.app (/home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/generators/app/index.js:141:15)
    at Object.<anonymous> (/home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/yeoman-generator/lib/base.js:431:23)
    at /home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/run-async/index.js:25:25
    at /home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/run-async/index.js:24:19
    at /home/[username]/.nvm/versions/node/v7.10.0/lib/node_modules/generator-restify-es-6/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by warrenca** [comment]
Thanks for reporting, I have updated the code and should be working now with the [v0.1.1](https://github.com/warrenca/generator-restify-es-6/tree/v0.1.1)!
